# Generated by Django 5.2.5 on 2025-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(default=2025),
        ),
    ]
