# Generated by Django 5.2.5 on 2025-09-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.IntegerField(null=True),
        ),
    ]
