# Generated by Django 5.2.5 on 2025-09-18 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
